---
- hosts: localhost 
  become: yes
  tasks:
    - name: Install Packages 
      yum: 
        name: 
           - curl 
           - git
           - unzip
           - wget
           - bind-utils
           - yum-utils
           - lvm-2 
           - device-mapper-persistent-data
        state: present 

    - name: create binary directory 
      file: 
        path: /etc/tempdownload 
        state: directory


    - name: download Vault binary 
      get_url: url=https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip dest=/etc/tempdownload

    - name: download Consul binary 
      get_url: url=https://releases.hashicorp.com/consul/1.7.1/consul_1.7.1_linux_amd64.zip dest=/etc/tempdownload

    - name: download Nomad binary
      get_url: url=https://releases.hashicorp.com/nomad/0.10.4/nomad_0.10.4_linux_amd64.zip dest=/etc/tempdownload

    - name: download Terraform Binary 
      get_url: url=https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip dest=/etc/tempdownload

    - name: download packer binary
      get_url: url=https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip dest=/etc/tempdownload

    - name: Unzip Vault Binary
      unarchive: 
        src: /etc/tempdownload/vault_1.3.2_linux_amd64.zip 
        dest: /usr/local/bin 

    - name: Unzip Consul binary 
      unarchive: 
        src: /etc/tempdownload/consul_1.7.1_linux_amd64.zip
        dest: /usr/local/bin

    - name: Unzip Nomad binary
      unarchive: 
        src: /etc/tempdownload/nomad_0.10.4_linux_amd64.zip
        dest: /usr/local/bin
    
    - name: Unzip Terraform binary
      unarchive: 
        src: /etc/tempdownload/terraform_0.12.23_linux_amd64.zip

    - name: Unzip Packer binary  
      unarchive:
        src: /etc/tempdownload/packer_1.5.4_linux_amd64.zip
        dest: /usr/local/bin 

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes
 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes



       
  