- hosts: localhost 
  become: yes
  tasks:
    - name: Install Packages 
      yum: 
        name: 
           - curl 
           - git
           - unzip
           - wget
        state: present 

    - name: create binary directory 
      file: 
        path: /etc/tempdownload 
        state: directory


    - name: download Vault binary 
      get_url: url=https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip dest=/etc/tempdownload

    - name: download Consul binary 
      get_url: url=https://releases.hashicorp.com/consul/1.7.1/consul_1.7.1_linux_amd64.zip dest=/etc/tempdownload

    - name: Unzip Vault Binary
      unarchive: 
        src: /etc/tempdownload/vault_1.3.2_linux_amd64.zip 
        dest: /usr/local/bin 

    - name: Unzip Consul binary 
      unarchive: 
        src: /etc/tempdownload/consul_1.7.1_linux_amd64.zip
        dest: /usr/local/bin



       
  