- hosts: localhost 
  become: yes
  become_user: root
  tasks:
    - name: Install Packages 
      yum: 
        name: 
           - curl 
           - git
           - unzip
           - wget
        state: present 

    - name: download vault binary 
      get_url: url=https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip 

    - name: Unzip Vault Binary
      unarchive: 
        src: vault_1.3.2_linux_amd64.zip 
        dest: /usr/local/bin 

       
  